[[main]]
none = "none"

[[main]]
name = "Baking"
pageRef = "baking"
identifier = "PZQOJE1Lcr"
weight = 9_999

[[main]]
name = "Cooking"
pageRef = "cooking"
identifier = "nAWT414SFp"
weight = 9_999

[[footer]]
none = "none"
